docs/Build/Concepts/overview.md
src/components/Features/Features.js
src/pages/index.js

These still contain the docs/docs/ issue

updated links from homepage

---

docs/Build/Chains/arbitrum.md
docs/Build/Chains/avalanche.md
docs/Build/Chains/binance-smart-chain.md
docs/Build/Chains/celo.md
docs/Build/Chains/ethereum.md
docs/Build/Chains/fantom.md
docs/Build/Chains/iotex.md
docs/Build/Chains/near.md
docs/Build/Chains/nervos.md
docs/Build/Chains/polygon.md
docs/Build/Chains/solana.md
sidebars.js

added arbitrum

---

src/components/Features/Features.js

fix the double docs issue in hardcoded links on the main docs page

fix the trailing /

---

README.md
docs/Earn/liquid-staking/liquid-staking.md

feat: STAKAN-1265

---

docs/Tutorials/submit-tutorial.md

Adds graphics & button to the tutorials page. 
Some grammatical edits included.

DOCS-24: Tutorials Page Updates

---

docs/Earn/liquid-staking/avax/stake-avax.md

* add aBNBc logo in PNG and SVG to brand-assets.md.
* brush up on stake-avax.md.

hotfix: STAKAN-1321 brush up on AVAX docs in addition (#203)

---

docs/Earn/bridge/bridge-introduction.md
docs/Earn/bridge/bridge-tokens.md

add briding option for aETHb, update bridging option for aMATICb, update bridging process explanation (#209)

hotfix: STAKAN-1325 update Bridge docs

---

docs/Game/Unity/getting-started/01-connect.md

- Amended Connect Wallet & Authenticate section

updated Unity SDK Connect Wallet

---

docs/earn/bridge/bridge-mechanics.md
docs/earn/bridge/bridge-overview.md
docs/earn/liquid-staking/bnb/bnb-liquid-staking-overview.md
docs/earn/liquid-staking/ftm/ftm-liquid-staking-overview.md
docs/game/unreal/getting-started/02-sending-transactions.md
docs/learn/tokens-governance/ankr-tokens.md
docs/learn/tokens-governance/how-governance-works.md
docs/learn/tokens-governance/how-to-buy-ankr-tokens.md
docs/learn/tokens-governance/how-to-make-a-proposal.md
docs/learn/tokens-governance/how-to-swap-assets-for-ankr-tokens.md
docs/learn/tokens-governance/how-to-vote-on-a-proposal.md
docs/learn/tokens-governance/tokenomics.md

* small fxies after the fact
* add links to BNB and FTM sec audit reports, move the audit details section to Overview for easier findability

fix: STAKAN-1330 add FTM LS and BNB LS audit reports (#231)

---

docs/earn/bridge/bridge-overview.md

* sentencecase headings in build-blockchain, earn, game, learn
* fix Bridge audit intro text

fix: DOCS-66 (#239)

---

src/components/Footer/Footer.js
src/components/Footer/Footer.module.css
src/pages/index.js
src/theme/Footer/index.js

Co-authored-by: Olle Solens <raproid@gmail.com>

add custom footer (#249)

---

docs/game/unity/overview.md
docs/game/unreal/overview.md

Adds YouTube video thumbnails to Unity SDK Overview page & corrects capitalization of page headers

DOCS-44: Add Unity SDK YouTube Videos to Game Docs

---

sidebars.js

* rename Earn to Staking
* rename Earn to Staking

STAKAN-1364 finish it! ankerality! (#291)

---

docs/build-blockchain/chains/v2/ethereum/how-to/basic-dapp.md
docs/build-blockchain/chains/v2/ethereum/how-to/connect-metamask.md
docs/build-blockchain/chains/v2/ethereum/how-to/make-requests.md
docs/build-blockchain/chains/v2/ethereum/how-to/send-transaction.md
sidebars.js

amended sidebar id

---

static/css/custom.css

Reverts Ankr-network/ankr-docs#300

Revert "Stage"

---

static/css/custom.css

Reverts Ankr-network/ankr-docs#304

Revert "Revert "Stage""

---

docs/game/unity/overview.md
docs/game/unreal/getting-started/00-before-you-start.md
docs/game/unreal/getting-started/01-connect-unreal.md
docs/game/unreal/getting-started/02-sending-transactions.md
docs/game/unreal/getting-started/03-update-nft.md
docs/game/unreal/getting-started/04-mint-nft.md
docs/game/unreal/overview.md
docs/game/unreal/v4.2.7.md

This pr adds Unreal tutorial videos to their respective docs pages.

Adding YouTube videos for Unreal

---

docs/game/unity/how-tos/update-events.md
sidebars.js

- Revised and edited full instructions for Events and Subscriptions.

Updated content for Events and Subscriptions

---

docs/build-blockchain/build-overview.md
docs/build-blockchain/get-started/ankr-protocol/premium-rpcs/01-get-ready/README.md
docs/build-blockchain/get-started/ankr-protocol/premium-rpcs/02-deposit-ankr.md
docs/build-blockchain/get-started/ankr-protocol/premium-rpcs/README.md
docs/build-blockchain/get-started/pricing-plans.md
docs/learn/tutorials/use-web3.py-to-interact-with-rpc-nodes.md

Remove outdated V2 Pricing
The following pages will be edited in this PR:
https://www.ankr.com/docs/build-blockchain/get-started/ankr-protocol/premium-rpcs/deposit-ankr/#assumptions
https://www.ankr.com/docs/learn/tutorials/connect-web3py/#01---connect-to-ankr-rpc-nodes
https://www.ankr.com/docs/build-blockchain/get-started/pricing/#public-rpcs-and-premium-plan
https://www.ankr.com/docs/build-blockchain/overview/
cc @raproid and @thedefidork

Remove 10000 Ankr for Premium Plan

---

static/css/custom.css

[DOCS-192]
[DOCS-192]: https://ankrnetwork.atlassian.net/browse/DOCS-192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: DOCS-192 remove extra horizontal scroll

---

README.md

another minor edit

---

docs/staking/liquid-staking/avax/avax-api.md
docs/staking/liquid-staking/bnb/bnb-api.md
docs/staking/liquid-staking/bnb/bnb-sdk.md
docs/staking/liquid-staking/eth/eth-sdk.md
docs/staking/liquid-staking/matic/matic-api.md
docs/staking/liquid-staking/matic/matic-sdk.md
docs/staking/sdk-overview.md
docusaurus.config.js
sidebars.js

https://ankrnetwork.atlassian.net/browse/DOCS-187

DOCS-187: add Staking SDK

---

docs/build-blockchain/build-overview.md
docs/build-blockchain/products/v2/01-public-community-rpcs.md
docs/build-blockchain/products/v2/premium-get-started.md
sidebars.js

Public and Private APIs merged under a single section, got rid of BNB Sidechain, Advanced API section moved to Products, Ankr Scan moved under Advanced APIs, Pricing info moved under RPC Services,

chore: DOCS-213 build docs restructure after feedback

---

sidebars.js

BNB Sidechain comeback. No more, no less.

chore: DOCS-213 BNB Sidechain comeback

---

docs/build-blockchain/concepts/pricing-plans.md
docusaurus.config.js
sidebars.js

Done according to: https://ankrnetwork.atlassian.net/browse/DOCS-216

feature: DOCS-216 Product pricing, PAYG, pricing calculator

---

docs/build-blockchain/products/v2/premium-endpoints.md
docs/build-blockchain/products/v2/premium-get-started.md
sidebars.js

Just did some magic with links for them to work properly.

chore: DOCS-243 Premium Tier links added while broken links fixed

---

docs/build-blockchain/products/advanced-apis/advanced-apis-overview.md
docs/build-blockchain/products/advanced-apis/nft-api.md
docs/build-blockchain/products/advanced-apis/query-api.md
docs/build-blockchain/products/advanced-apis/token-api.md
docs/build-blockchain/products/v2/advanced-apis.md
sidebars.js
static/css/custom.css

Done according to: https://ankrnetwork.atlassian.net/browse/DOCS-244

feat: DOCS-244 Advanced APIs migrated, enriched with info, css updated

---

docs/build-blockchain/concepts/pricing-plans.md

Done according to: https://ankrnetwork.atlassian.net/browse/DOCS-294

chore: DOCS-294 Build pricing prettify

---

docs/staking/delegated-staking/mgno/stake.md

…nal docs and fix the wrong link in them.

DOCS-328: host instructions how to convert GNO to mGNO from the original docs and fix the wrong link in them

---

docs/staking/liquid-staking/bnb/bnb-liquid-staking-mechanics.md
docs/staking/liquid-staking/bnb/bnb-liquid-staking-unstake.md

…nal docs and fix the wrong link in them.

DOCS-335: Add unstaking details for BNB Liquid Staking

---

pages/staking/for-integrators/overview.md
pages/staking/for-integrators/sdk/liquid-staking-sdk.md
pages/staking/for-integrators/smart-contract-api/overview.md

DOCS-375, DOCS-374: rearrange links, include links to LS APIs

---

package.json
pages/advanced-api/_meta.json
pages/advanced-api/specification.mdx
src/styles/global.css
yarn.lock

Nested Advanced API OpenAPI specification with redoc UI

Add Advanced API OAS3 page

---

pages/rpc-service/chains/chains-api/solana.md
pages/rpc-service/chains/chains-list.md
pages/staking/delegated-staking/gnosis/faq.md

Done according to https://ankrnetwork.atlassian.net/browse/DOCS-486

feature: DOCS-486 Solana API Reference

---

pages/staking/extra/ankr-validators.md
pages/staking/for-integrators/dev-details/avax-liquid-staking-mechanics.md

https://ankrnetwork.atlassian.net/browse/DOCS-524
What: ditto
How: [Ankr 4](https://avascan.info/staking/validator/NodeID-5Uf5RUZ89pWtYj4Sgc7pxf1mkq2f4EEMW)
Where: ankr-validators and avax-liquid-staking-mechanics

DOCS-524: [add] Ankr #4 validator on Avalanche 

---

pages/staking/extra/liquid-staking-fees.md

https://ankrnetwork.atlassian.net/browse/DOCS-532
What: ditto
How: 10% fees from rewards
Where: Staking > Extra > Fees

DOCS-532: [update] ETH LS fees in Staking > Extra > Fees

---

pages/staking/for-integrators/restful-api/staking-metrics.md

https://ankrnetwork.atlassian.net/browse/DOCS-533
What: ditto
How: The formula is: `rewards_for_last_7_days / staked_amount * 5200`.
Where: https://www.ankr.com/docs/staking/for-integrators/restful-api/staking-metrics/

DOCS-533: [add] APY formula in Restful API > Staking Metrics

---

.github/workflows/deploy.yml
.gitignore

[STAKAN-2640]
[STAKAN-2640]: https://ankrnetwork.atlassian.net/browse/STAKAN-2640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: STAKAN-2640 use new repo for generating sdk auto docs

---

next.config.mjs
theme.config.tsx

[revert] to unoptimized images

---

src/components/FooterMenu.jsx

https://ankrnetwork.atlassian.net/browse/SEO-139

feat: SEO-139 Removed rel attribute from footer links

---

pages/advanced-api/javascript-sdk.mdx
pages/advanced-api/token-api.mdx
pages/advanced-tutorials/donation-based-crowdfunding-dapp-on-polygon-with-ankr.mdx
pages/automation/create-compatible-contracts.mdx
pages/automation/custom-logic-automation.mdx
pages/automation/manage-tasks.mdx
pages/automation/time-based-automation.mdx
pages/basic-tutorials/backend-nodejs-ipfs-file-uploader-with-filebase.mdx

Rectify typographical inaccuracies
This PR addresses several typographical errors across various files in the project. The changes improve readability and maintain the professional standard of the documentation and code comments.
Justification
Typographical errors, while minor, can detract from the overall quality of the project. Correcting these errors ensures clarity and professionalism, making the project more accessible and understandable for current and future contributors.

Docs improvements

---

pages/staking-extra/compatible-wallets.mdx

Please add Gem Wallet for compatible wallet.
Ankr validators are added as an option.

add Gem Wallet to compatible-wallets.mdx
